### PR TITLE
use tls

### PR DESCRIPTION
**Pull request by s1lvester**
Again. Just a little OCD.

Btw: Is it possible to use tls when zeroconf-authenticating to apresponse.spotify.com?

### CODE REVIEW

**Comment by plietar** [comment]
Using https to connect to apresolve would put a dependency on openssl, which can be painful to link to especially on macOS.
It's already an optional dependency for Facebook support though, so https could be used when openssl is already present. Happy to merge a PR for that.

That being said, if an attacker can MITM the connection to apresolve, it could MITM the connection to the actual AP as well. librespot doesn't have any way of authenticating Spotify's server, and will happily send the username and password to the attacker. I don't know what the official client does about it. Probably worth investigating (and writing a simple MITM proxy).

**Comment by plietar** [comment]
#125

**Comment by sashahilton00** [comment]
I have no idea what the actual library does, but one way to do it that should be relatively easy to implement would be certificate fingerprinting. Spotify uses a wildcard certificate, so we'd only ever need to check against one fingerprint. At the time of writing the fingerprint for `*.spotify.com` is `7A:27:2B:23:A6:D1:6D:34:73:35:7D:E5:4B:96:56:BA:2C:CC:EC:EC` though at the same time adding this as a check will mean that we have to keep an eye out for certificate updates/revocations by Spotify.

**Comment by plietar** [comment]
@sashahilton00 Replied in #125

**Comment by sashahilton00** [comment]
My bad, read apresponse.spotify.com as apresolve.spotify.com. Was just thinking that if someone is bothering to spoof [http://apresolve.spotify.com/](http://apresolve.spotify.com/) then you've most likely got bigger problems to deal with :)

**Pull request merged**
