### PR TITLE
update deps to compile (and work) also on arm devices

### PR DESCRIPTION
**Pull request by herrernst**

### CODE REVIEW

**Comment by plietar** [comment]
Cool thanks.
Out of interest, what arm device did you get it to work on ?

**Comment by herrernst** [comment]
You're welcome.
I'm running on an Raspberry Pi 2, I directly compiled on the device (Debian) with the pre-built Rust binaries from https://github.com/warricksothr/RustBuild because I didn't want to care about cross compilation issues when linking to system libraries (like portaudio); building of course takes longer than on a PC.
It works really well, the only thing that bugs me for now (not related to arm) is #26 (I'm using ALSA, so while librespot is running, no other process can play audio, even if librespot doesn't play anything/isn't selected as output device). I would be very happy if you could take a look into it some time :)
Thanks again!

**Comment by plietar** [comment]
I'm away for the week, so I won't be able to work on it, but I 'll have a look when I get back

**Comment by herrernst** [comment]
Thanks ;)

**Pull request merged**
