### PR TITLE
Add initial support for ALSA mixer

### PR DESCRIPTION
**Pull request by joerg-krause**
The ALSA mixer module implements a simple linear volume control. Note, that a linear volume control is not ideal for human audio experience as our ears respond to sound on an exponential curve.

The mixer also works fine with the ALSA softvol plugin which offers an logarithmic attenuation curve.

**TODO**: Use logarithmic curve for hardware mixers.

### CODE REVIEW

**Comment by jsopenrb** [comment]
Volume calculation fails for maximum volume values. If the range is 0..255 then at full volume the result will be 256 instead of 255. I suppose it should not use integer math because volume range can have very different values.

**Comment by joerg-krause** [comment]
Not sure what do you mean. The mixer uses `get_playback_volume_range()` to get the actual range.

**Comment by jsopenrb** [comment]
Yes, but then you add one to that range, so for 0..255 at max volume the
resulting volume is 256 instead of 255.

On Wednesday, March 15, 2017, Jörg Krause <notifications@github.com> wrote:
> Not sure what do you mean. The mixer uses get_playback_volume_range() to
get the actual range.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/iVB_IHPdVhUghRc1w6iFL7sz5ZWPm2tTGJe3eGNbAdIXtfxoXO_m9LY1LBXbk8LjAZLtoB6Qm0lwbQj5Nvd6vxiwWKLKdSFklatn_7E-VvqIszXdbrwCIDhmwaAp8R3IsJPsVKwoafEP40x2IuAagk-vysavNQ=s0-d-e1-ft#https://github.com/notifications/beacon/ASkHhFFswsvqcGruje2ivD0jC6XfTkjsks5rmEBSgaJpZM4MX194.gif>

**Comment by joerg-krause** [comment]
Yes, 256 is the resolution if the range is from 0 to 255. The resolution is used to get the factor wrt the spotify resolution, which is 65536 / 256 = 256 in this case. If the max spotify volume of 65535 is set this results in 65535 / 256 = 255.99..., which is truncated to 255 because of the Integer. But I can see now what you mean. I need to add 1 to the spotify volume and substract it after the division: ((65535 + 1) / 256) - 1 = 255.

I will update the commit tomorrow.

**Comment by joerg-krause** [comment]
@jsopenrb I've updated the volume calculation...

**Comment by jsopenrb** [comment]
Better, but it will still fail for certain volume ranges like 190. I think the proper solution it to switch to float calculations. Not a big deal at the moment.

**Comment by plietar** [comment]
Unfortunately I don't have much time at the moment to test this, it'll have to wait another week or two.

FWIW, I've previously used the following code to set the volume, which seemed to produced good results on my Pi's builtin audio output

```rust
    let (min, max) = elem.get_playback_db_range();
    let db_volume = if volume == 0 {
        min
    } else {
        let volume = volume as f64 / 65535.;
        let volume = volume.log10() * 6000.;
        MilliBel(volume as i64) + max
    };

    self.elem.set_playback_db_all(db_volume, alsa::Round::Ceil).unwrap();
```

**Comment by joerg-krause** [comment]
No, problem! Take your time. I'll check your volume setting...

**Comment by jsopenrb** [comment]
That volume setting assumes that minimal dB value is mute which is not true for all cards.
get_normalized_volume/set_normalized_volume from alsa-utils have full implementation and handle both cases of minimum dB values:
http://git.alsa-project.org/?p=alsa-utils.git;a=blob;f=alsamixer/volume_mapping.c;h=1c0d7c45e6686239464e1b0bbc8983ea57f3914f;hb=HEAD
Shouldn't be too hard to rewrite those :)

**Comment by joerg-krause** [comment]
`snd_mixer_selem_get_playback_dB_range()` only worka for hardware mixers, but not for the ALSA softvol plugin where `snd_ctl_get_dB_range()` has to be used to get the db range of the control element.

This is the relevant code, how the handling of hardware and software mixer is done in shairtport-sync: https://github.com/mikebrady/shairport-sync/blob/master/audio_alsa.c#L358-L396. The ALSA softvol plugin is handled as a special case of a hardware mixer. The software mixer is used if no hardware mixer and no ALSA softvol plugin is used.

Note, shairport-sync uses an own attenuation curve, which is mapped onto the mixer. That's make the volume handling more complex than it is necessary for librespot.

For hardware mixer, we need a logarithmic curve, but not for the ALSA softvol plugin, as it already maps the linear volume value to a logarithmic curve.

So, maybe we need to split the mixer into two mixers: *alsa* and *alsasoftvol*?

**Comment by joerg-krause** [comment]
Project is dead and pull request has moved to https://github.com/librespot-org/librespot/pull/245.

Closing.

**Pull request closed without merging**
