### PR TITLE
Pulseaudio backend

### PR DESCRIPTION
**Pull request by marcust**

### CODE REVIEW

**Comment by marcust** [comment]
These type error still puzzle me, for me it compiles....

**Comment by marcust** [comment]
```
let bytes = data.len() as u64 * 2;
```

is definitely not platform independent, but I don't know how to do it better. What's the native type for size_t in Rust?

**Comment by marcust** [comment]
And, is there any way to make travis use pulse?

**Comment by plietar** [comment]
Add `libpulse-dev` to the list of packages in `.travis.yml`

**Pull request merged**
